base = "/" 
publish = "/build" 
command = "npm run build"

[functions]
  directory = "/src/netlify-functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/artist/:artistId"
  to = "/src/netlify-functions/artists-data"
  status = 200
